version: '3'

services:
  ipfs:
    #image: linuxserver.io/linuxserver/ipfs:latest
    #image: ipfs/go-ipfs:latest
    image: linuxserver/ipfs:latest
    container_name: graffiti-ipfs
    restart: unless-stopped
    ports:
      - 4001:4001/tcp # ipfs swarm
      - 5001:5001/tcp # ipfs api
      - 8081:8080/tcp # ipfs gateway
      - 4443:443/tcp # https web ui
    volumes:
      # :z for SELinux
      - ./data/ipfs:/data/ipfs:z
    healthcheck:
      test: ["CMD-SHELL", "ipfs swarm peers"]
      interval: 5s
      timeout: 10s
      retries: 30
  collection:
    container_name: graffiti-collection
    build: './collection'
    ports:
      - "8083:8083" # collection api
    command: ["./wait-for", "ipfs:5001", "--", "graffiti"]
    depends_on:
      - "ipfs"
  map:
    container_name: graffiti-map
    build: './map'
    ports:
      - "4567:3000" # map ui (<host_ip>:4567)
    depends_on:
      - "ipfs"
      - "collection"
  #test:
    #container_name: test
    #image: gotechnies/alpine-ssh
    #ports:
      #- "2222:22"
