version: '3'

services:
  ipfs:
    image: linuxserver/ipfs:latest
    container_name: graffiti-ipfs
    restart: unless-stopped
    networks:
      - ipfs
    ports:
      - 4001:4001/tcp # ipfs swarm
      - 127.0.0.1:5001:5001/tcp # ipfs api
      - 8080:8080/tcp # ipfs gateway
    volumes:
      - ./data/ipfs:/data/ipfs:z # :z for SELinux
    healthcheck:
      test: ['CMD-SHELL', 'ipfs swarm peers']
      interval: 5s
      timeout: 10s
      retries: 30
  collection:
    container_name: graffiti-collection
    restart: unless-stopped
    build: './collection'
    networks:
      - ipfs
      - collection
    ports:
      - 8083:8083/tcp # collection api
    command: ['ping', '-c', '1', 'ipfs:5001']
    depends_on:
      - ipfs
    environment:
      - VIRTUAL_HOST=domain.com
      - LETSENCRYPT_HOST=domain.com
    healthcheck:
      test: ['CMD-SHELL', 'ping -c 1 ipfs:5001']
      interval: 5s
      timeout: 10s
      retries: 30
  map:
    container_name: graffiti-map
    build: './map'
    networks:
      - collection
    ports:
      - 3000:3000/tcp # map ui
    depends_on:
      - ipfs
      - collection
  nginx:
    build: './nginx'
    container_name: graffiti-nginx
    networks:
      - collection
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: always
networks:
  ipfs:
    driver: bridge
  collection:
    driver: bridge
