version: '3'

services:
  map:
    build: './map'
    ports:
          - "4567:4567"
    depends_on:
      - "collection"
    #command: ["./wait-for", "map:8083", "--", "npm", "start"]
  collection:
    build: './collection'
    ports:
         - "8083:8083"
    depends_on:
      - "ipfs"
    command: ["./wait-for", "ipfs:5001", "--", "graffiti"]
  ipfs:
    container_name: graffiti-ipfs
    image: ipfs/go-ipfs
    ports:
          - "4001:4001"
          - "5001:5001"
          - "8080:8080"
    volumes:
      - /data/ipfs:/data/ipfs/
    healthcheck:
      test: ["CMD-SHELL", "ipfs swarm peers"]
      interval: 5s
      timeout: 10s
      retries: 30
  test:
    container_name: test
    image: gotechnies/alpine-ssh
    ports:
          - "2222:22"
