version: '3'

services:
  ipfs:
    container_name: graffiti-ipfs
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001" # ipfs swarm
      - "5001:5001" # ipfs api
      - "8081:8080" # ipfs gateway
    volumes:
      - ./data/ipfs:/data/ipfs/
    healthcheck:
      test: ["CMD-SHELL", "ipfs swarm peers"]
      interval: 5s
      timeout: 10s
      retries: 30
  collection:
    container_name: graffiti-collection
    build: './collection'
    ports:
      - "8083:8083" # collection api
    command: ["./wait-for", "ipfs:5001", "--", "graffiti"]
    depends_on:
      - "ipfs"
  map:
    container_name: graffiti-map
    build: './map'
    ports:
      - "4567:3000" # map ui (<host_ip>:4567)
    depends_on:
      - "ipfs"
      - "collection"
  test:
    container_name: test
    image: gotechnies/alpine-ssh
    ports:
      - "2222:22"
